package br.com.contabilidade.chatbot.entity;

public enum TipoAtendimento {
    TRIAGEM_INICIAL,
    ABRIR_EMPRESA,
    REGULARIZAR_MEI,
    EMITIR_DAS,
    IMPOSTO_DE_RENDA,
    FOLHA_DE_PAGAMENTO,
    CERTIDOES_NEGATIVAS,
    CLIENTE_DEPARTAMENTO_PESSOAL,
    CLIENTE_FISCAL,
    CLIENTE_PARALEGAL,
    CLIENTE_VERIFICACAO,
    FALAR_COM_CONTADOR,
    ENVIAR_DOCUMENTOS
}
